version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: anythingllm-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=anythingllm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - anything-llm-net

volumes:
  postgres_data:

networks:
  anything-llm-net:
    driver: bridge
