[build]
builder = "nixpacks"

[build.env]
NODE_ENV = "production"

[deploy]
startCommand = "cd server && npx prisma generate --schema=./prisma/schema.prisma && npx prisma migrate deploy --schema=./prisma/schema.prisma && SERVER_PORT=$PORT node index.js"
healthcheckPath = "/api/ping"
healthcheckTimeout = 30

[variables]
NODE_ENV = "production"