[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/ping"
healthcheckTimeout = 180
healthcheckInterval = 10
restartPolicyType = "on_failure"
restartPolicyMinDelay = 1000

[deploy.env]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
NODE_OPTIONS = "--max-old-space-size=4096"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
