[build]
builder = "nixpacks"
buildCommand = "echo '[RAILWAY] Build starting...' && npm install -g yarn && cd server && yarn install --production"

[deploy]
root = "server"
startCommand = "echo '[RAILWAY] Starting Prisma operations...' && npx prisma generate --schema=./server/prisma/schema.prisma && echo '[RAILWAY] Prisma generate completed' && (npx prisma migrate deploy --schema=./server/prisma/schema.prisma || echo '[RAILWAY] Migrate failed but continuing...') && echo '[RAILWAY] Prisma migrate completed' && echo '[RAILWAY] Starting Node.js server...' && node server/index.js"
healthcheckPath = "/api/ping"
healthcheckTimeout = 180
healthcheckInterval = 10
restartPolicyType = "on_failure"
restartPolicyMinDelay = 1000

[deploy.env]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
