[build]
builder = "nixpacks"

[deploy]
root = "server"
startCommand = "npx prisma generate && npx prisma migrate deploy && node index.js"
healthcheckPath = "/api/ping"
healthcheckTimeout = 120

[deploy.env]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
