[build]
builder = "nixpacks"
buildCommand = "echo '[RAILWAY] Build starting...' && cd server && npm install --omit=dev --legacy-peer-deps"

[deploy]
root = "server"
startCommand = "echo '[RAILWAY] Starting Prisma operations...' && npx prisma generate --schema=./prisma/schema.prisma && echo '[RAILWAY] Prisma generate completed' && (npx prisma migrate deploy --schema=./prisma/schema.prisma || echo '[RAILWAY] Migrate failed but continuing...') && echo '[RAILWAY] Prisma migrate completed' && echo '[RAILWAY] Starting Node.js server...' && node index.js"
healthcheckPath = "/api/ping"
healthcheckTimeout = 180
healthcheckInterval = 10
restartPolicyType = "on_failure"
restartPolicyMinDelay = 1000

[deploy.env]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
