[build]
builder = "nixpacks"
buildCommand = "echo '[RAILWAY] Build starting...' && npm install -g yarn && echo '[RAILWAY] Installing frontend dependencies...' && cd frontend && yarn install && echo '[RAILWAY] Building frontend...' && yarn build && echo '[RAILWAY] Copying frontend build to server/public...' && cd .. && cp -R frontend/dist server/public && echo '[RAILWAY] Installing server dependencies...' && cd server && yarn install --production && echo '[RAILWAY] Ensuring Prisma schema is available...' && ls -la prisma/schema.prisma && echo '[RAILWAY] Build completed successfully'"

[deploy]
root = "server"
startCommand = "echo '[RAILWAY] Starting Prisma operations...' && npx prisma generate --schema=./prisma/schema.prisma && echo '[RAILWAY] Prisma generate completed' && (npx prisma migrate deploy --schema=./prisma/schema.prisma || echo '[RAILWAY] Migrate failed but continuing...') && echo '[RAILWAY] Prisma migrate completed' && echo '[RAILWAY] Starting Node.js server...' && node index.js"
healthcheckPath = "/api/ping"
healthcheckTimeout = 180
healthcheckInterval = 10
restartPolicyType = "on_failure"
restartPolicyMinDelay = 1000

[deploy.env]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
