[build]
builder = "nixpacks"

[build.env]
NODE_ENV = "production"

[deploy]
root = "server"
preDeployCommand = "npm install --omit=dev --legacy-peer-deps"
startCommand = "NODE_ENV=production npx prisma generate --schema=./prisma/schema.prisma && npx prisma migrate deploy --schema=./prisma/schema.prisma && NODE_ENV=production SERVER_PORT=$PORT node index.js"
healthcheckPath = "/api/ping"
healthcheckTimeout = 30



[services.collector]
[services.server]
root = "server"
preDeployCommand = "npm install --omit=dev --legacy-peer-deps"
startCommand = "npx prisma generate --schema=./prisma/schema.prisma && npx prisma migrate deploy --schema=./prisma/schema.prisma && SERVER_PORT=$PORT node index.js"
healthcheckPath = "/api/ping"
healthcheckTimeout = 30

[services.collector]
preDeployCommand = "npm install --omit=dev --legacy-peer-deps"
startCommand = "NODE_ENV=production node index.js"
healthcheckPath = "/"
healthcheckTimeout = 30
