[build]
builder = "nixpacks"
buildCommand = "npm install -g yarn && cd frontend && yarn install && yarn build && cd .. && cp -R frontend/dist server/public && cd server && yarn install --production"

[deploy]
root = "server"
startCommand = "npx prisma migrate deploy && node index.js"
healthcheckPath = "/api/ping"
healthcheckTimeout = 180
healthcheckInterval = 10
restartPolicyType = "on_failure"
restartPolicyMinDelay = 1000

[deploy.env]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
